// export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
// export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
// export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
// export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
// export const GET_TOPICS = 'GET_TOPICS';
// export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
// export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
// export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
// export const INCREMENT_COUNT = 'INCREMENT_COUNT';
// export const DECREMENT_COUNT = 'DECREMENT_COUNT';
// export const DESTROY_TOPIC = 'DESTROY_TOPIC';
// export const TYPING = 'TYPING';

/**
 * User actions constant
 * @type {string}
 */
export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

/**
 * Navigation bar actions constant
 * @type {string}
 */
export const SET_NAVIGATION_ITEM_ACTIVE = 'SET_NAVIGATION_ITEM_ACTIVE';
export const SET_NAVIGATION_CONTENT = 'SET_NAVIGATION_CONTENT';
export const SET_MENUITEM_OPEN_CLOSE = 'SET_MENUITEM_OPEN_CLOSE';

/**
 * Plugins repository actions constant
 * @type {string}
 */
/* Private Plugin Actions */
export const CREATE_PLUGIN_REQUEST = 'CREATE_PLUGIN_REQUEST';
export const CREATE_PLUGIN_SUCCESS = 'CREATE_PLUGIN_SUCCESS';
export const CREATE_PLUGIN_FAILURE = 'CREATE_PLUGIN_FAILURE';
export const GET_PLUGINS_REQUEST = 'GET_PLUGINS_REQUEST';
export const GET_PLUGINS_SUCCESS = 'GET_PLUGINS_SUCCESS';
export const GET_PLUGINS_FAILURE = 'GET_PLUGINS_FAILURE';
export const SHOW_NOTIFICATION_DONE = 'SHOW_NOTIFICATION_DONE';
export const RESET_STORE_STATES = 'RESET_STORE_STATES';
export const SET_DATATABLE_SELECTED_DATA = 'SET_DATATABLE_SELECTED_DATA';
export const UPDATE_PLUGIN_REQUEST = 'UPDATE_PLUGIN_REQUEST';
export const UPDATE_PLUGIN_SUCCESS = 'UPDATE_PLUGIN_SUCCESS';
export const UPDATE_PLUGIN_FAILURE = 'UPDATE_PLUGIN_FAILURE';
export const DELETE_PLUGIN_REQUEST = 'DELETE_PLUGIN_REQUEST';
export const DELETE_PLUGIN_SUCCESS = 'DELETE_PLUGIN_SUCCESS';
export const DELETE_PLUGIN_FAILURE = 'DELETE_PLUGIN_FAILURE';
export const DOWNLOAD_PLUGIN_SUCCESS = 'DOWNLOAD_PLUGIN_SUCCESS';
export const DOWNLOAD_PLUGIN_FAILURE = 'DOWNLOAD_PLUGIN_FAILURE';
